#pragma once

//
// This file contains all IDs of game assets 
//

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_GOOMBA_PRO	20001
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_HIDDEN_BLOCK -1
#define OBJECT_TYPE_HIDDEN_BLOCK_MARIO -2
#define OBJECT_TYPE_HIDDEN_BLOCK_KOOPA -3
#define OBJECT_TYPE_HIDDEN_BLOCK_GOOMBA -4
#define OBJECT_TYPE_DIE_BLOCK -5
#define OBJECT_TYPE_QUESTION_BOX 6
#define OBJECT_TYPE_QUESTION_BOX_COIN 60001
#define OBJECT_TYPE_QUESTION_BOX_MUSHROOM 60002
#define OBJECT_TYPE_MUSHROOM 7
#define OBJECT_TYPE_CHOMPER 8
#define OBJECT_TYPE_CHOMPER_SMALL 81
#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_BOTTOM_BAR	-10
#define OBJECT_TYPE_MARIO_MAP	9
#define OBJECT_TYPE_LIGHT_BRICK 20
